# Generated by Django 5.0.2 on 2025-11-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('seccion', models.CharField(max_length=3)),
                ('dias', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=15)),
                ('programa', models.CharField(max_length=60)),
                ('creditos', models.PositiveIntegerField()),
                ('maestro_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_escolar_desit_api.maestros')),
            ],
        ),
    ]
