# Generated by Django 5.0.2 on 2025-11-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0004_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='dias',
            field=models.CharField(max_length=100),
        ),
    ]
